exports.Areas=[
 {
"CityId": 621,
"areaName" :"فرامه",
"area type" : "محله",
"longtitude" : 35.71258,
"latitude" :52.06507,
"locationDescription":"بافت میانی شهر",
"subwayAvailability" : "خیابان فرهنگ",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی",
"areaNature" : ["رودخانه تار",""],
"areaTemplate":"بافت قدیم",
"humanTissue" : "بومی",
 "ReginonalPrice":"",
"floorArea":"",
"landUse":"مسکونی",
},


 {
"CityId": 621,  
"areaName" :"چالکا",
"area type" : "محله",
"longtitude" : 35.72214,
"latitude" :52.07501,
"locationDescription":"بافت میانی شهر",
"subwayAvailability" : "خیابان دانشگاه",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی",
"areaNature" : "",
"areaTemplate":"بافت قدیم",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
 "landUse":"مسکونی،باغات،کشاورزی",
},


{
"CityId": 621,
"areaName" :"درویش",
"area type" : "محله",
"longtitude" : 35.72608,
"latitude" :52.06640,
"locationDescription":"بافت میانی شهر",
"subwayAvailability" : "میدان هفده شهریور",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی",
"areaNature" : "رودخانه تار",
"areaTemplate":"بافت قدیم",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی،باغات،",
},

{
"CityId": 621,
"areaName" :"قاضی",
"area type" : "محله",
"longtitude" : 35.719278,
"latitude" :52.07006,
"locationDescription":"بافت میانی شهر",
"subwayAvailability" : "بلوار امام حسین",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی",
"areaNature" : "رودخانه تار",
"areaTemplate":"بافت قدیم",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی،باغات،،",
},

{
"CityId": 621,
"areaName" :"روح افزا",
"area type" : "محله",
"longtitude" :35.72902 ,
"latitude" :52.07195,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "خیابان روح افزا",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی",
"areaNature" : "آبشار آیینه رود روح افزا,رودخانه تار",
"areaTemplate":"بافت ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی،باغات،،",
},

{
"CityId":621,
"areaName" :"اوره",
"area type" : "محله",
"longtitude" :35.73946 ,
"latitude" :52.06648,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "خیابان اوره",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی چشمه اعلا",
"areaNature" : "باغات",
"areaTemplate":"بافت قدیم و ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی،باغات",
},

{
"CityId":621,
"areaName" :"دشتبان",
"area type" : "محله",
"longtitude" :35.74444 ,
"latitude" :52.06371,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "خیابان چشمه اعلا",
"busAndTaxi" : "ایستگاه تاکسی چشمه اعلا",
"areaNature" : "",
"areaTemplate":"بافت قدیم و ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی،باغات",
},


{
"CityId":621,
"areaName" :"دشتمزار",
"area type" : "محله",
"longtitude" :35.74334 ,
"latitude" :52.07348,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "خیابان دشتمزار",
"busAndTaxi" : "ایستگاه تاکسی دشتمزار",
"areaNature" : "چشمه دشتمزار",
"areaTemplate":"بافت روستایی و بافت ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی،باغات",
},


{
"CityId":621,
"areaName" :"احمدآباد",
"area type" : "محله",
"longtitude" :35.73531 ,
"latitude" :52.05966,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "جاده چشمه اعلا",
"busAndTaxi" : "در مسیر تاکسی چشمه اعلا",
"areaNature" : "چشمه احمد اباد",
"areaTemplate":"  بافت قدیم و ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی،باغات",
},

{
"CityId":621,
"areaName" :"چشمه اعلا",
"area type" : "محله",
"longtitude" : 35.74540,
"latitude" :52.054700,
"locationDescription":"محلات شمالی ",
"subwayAvailability" : "جاده چشمه اعلا",
"busAndTaxi" : "نزدیک به ایستگاه تاکسی",
"areaNature" : ["چشمه اعلا","چشمه کهریز"],
"areaTemplate":"بافت قدیمی و بافت ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی،باغات،",
},


{
"CityId":621,
"areaName" :"مشاء",
"area type" : "محله",
"longtitude" :35.76691,
"latitude" :52.02787,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "جاده آبعلی مشاء",
"busAndTaxi" : "ایستگاه تاکسی مشاء",
"areaNature" : "",
"areaTemplate":"بافت ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی و کشاورزی و باغات",
},

{
"CityId":621,
"areaName" :"دشتک",
"area type" : "محله",
"longtitude" :"",
"latitude" :"",
"locationDescription":"محلات شمالی",
"subwayAvailability" : "جاده آبعلی مشاء",
"busAndTaxi" : "ایستگاه تاکسی مشاء",
"areaNature" : "",
"areaTemplate":"بافت ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی و کشاورزی و باغات",
},

{
"CityId":13,
"areaName" :"منظریه",
"area type" : "روستا",
"longtitude" :"",
"latitude" :"",
"locationDescription":"محلات شمالی",
"subwayAvailability" : "جاده آبعلی مشاء",
"busAndTaxi" : "ایستگاه تاکسی مشاء",
"areaNature" : "",
"areaTemplate":"بافت ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ویلایی و کشاورزی و باغات",
},

{
"CityId":621,
"areaName" :"امامزاده هاشم",
"area type" : "محله",
"longtitude" :35.77956,
"latitude" :52.03907,
"locationDescription":"محلات شمالی",
"subwayAvailability" : "جاده هراز",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "خالی از سکنه",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"زیارتگاه و ورزشی",
},

{
"CityId":700,
"areaName" :"آبعلی",
"area type" : "روستا",
"longtitude" :35.76760,
"latitude" :51.96671,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "دارد",
"areaNature" : "رودخانه آبعلی",
"areaTemplate":"بافت قدیم و ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"تجاری و مسکونی و باغات",
},

{
"CityId":700,
"areaName" :"تجرک",
"area type" : "محله",
"longtitude" :35.76167,
"latitude" :51.92155,
"locationDescription":"مجاورت بام رودهن",
"subwayAvailability" : "جاده دماوند",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"بافت روستایی",
"humanTissue" : "بومی ",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":700,
"areaName" :"وسکاره",
"area type" : "روستا",
"longtitude" :35.76698,
"latitude" :51.89568,
"locationDescription":"خیابان سجادیان رودهن",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"بافت قدیمی وویلایی",
"facalities" : "شهرک امام خمینی",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":700,
"areaName" :"آردینه",
"area type" : "روستا",
"longtitude" :35.79472,
"latitude" :51.88545,
"locationDescription":"دهستان آبعلی",
"subwayAvailability" : "آبعلی",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":700,
"areaName" :"جورد",
"area type" : "محله",
"longtitude" :35.80739,
"latitude" :51.86959,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی"
},


{
"CityId":700,
"areaName" :"رودهن",
"area type" : "محله",
"longtitude" :35.73061,
"latitude" :51.90757,
"locationDescription":"مجاورت جاده هراز",
"subwayAvailability" : "جاده دماوند",
"busAndTaxi" : "دارد",
"areaNature" : "رودخانه رودهن",
"areaTemplate":"بافت قدیم و جدید",
"humanTissue" : "بومی،مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی،باغات",
},

{
"CityId":700,
"areaName" :"چناران",
"area type" : "روستا",
"longtitude" :35.69747,
"latitude" :51.96528,
"locationDescription":"توابع رودهن",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",

"floorArea":"",
"landUse":"",
},

{
"CityId":700,
"areaName" :"گلاهک",
"area type" : "روستا",
"longtitude" :35.71893,
"latitude" :51.94903,
"locationDescription":"توابع رودهن",
"subwayAvailability" : "جاده دماوند-فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},
{
"CityId":621,
"areaName" :"بنیاد",
"area type" : "محله",
"longtitude" :35.71792,
"latitude" :52.054700,
"locationDescription":"",
"subwayAvailability" : " خیابان دانشگاه",
"busAndTaxi" : "ایستگاه تاکسی دارد",
"areaNature" : "کوه تلکمر به ارتفاع 2780متر",
"areaTemplate":"",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"florArea":"",
"landUse":"",
},

{
"CityId":621,
"areaName" :"شهرک آویشن",
"area type" : "محله",
"longtitude" :35.73183,
"latitude" :52.04586,
"locationDescription":"در مجاورت بنیاد",
"subwayAvailability" : "بلوار آویشن",
"busAndTaxi" : "ایستگاه تاکسی بنیاد",
"areaNature" : "کوه تلکمر",
"areaTemplate":"ویلایی",
"humanTissue" : "مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"ویلایی ،گردشگری",
},

{
"CityId":621,
"areaName" :"جیلارد",
"area type" : "محله",
"longtitude" : 35.69008,
"latitude" :52.04051,
"locationDescription":"محلات جنوبی",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "ندارد",
"areaNature" : "",
"areaTemplate":"بافت قدیمی و ویلایی",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},

{
"CityId":621,
"areaName" :"ولیران",
"area type" : "محله",
"longtitude" :35.69782 ,
"latitude" :52.05912,
"locationDescription":"",
"subwayAvailability" : "خیابان ولیران",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"روستایی",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},

{
"CityId":621,
"areaName" :"شلمبه",
"area type" : "محله",
"longtitude" :35.68563 ,
"latitude" :52.05236,
"locationDescription":"محلات جنوبی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "رودخانه تار",
"areaTemplate":"بافت روستایی و ویلایی", 
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},
{
"CityId":621,
"areaName" :"کالدشت ",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},



{
"CityId":621,
"areaName" :"خمینی آباد",
"area type" : "محله",
"longtitude" :35.71936 ,
"latitude" :52.07434,
"locationDescription":"خیابان منتهی به چنارشرق",
"subwayAvailability" : "خیابان منتهی به چنارشرق",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"بافت قدیمی",
"humanTissue" : "مهاجر و بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ",
},
 
 {
"CityId":621,
"areaName" :"چنارشرق",
"area type" : "روستا",
"longtitude" :35.69806 ,
"latitude" :52.10991,
"locationDescription":"محلات شرقی",
"subwayAvailability" : "جاده چنار",
"busAndTaxi" : "دارد",
"areaNature" : "چشمه و کوه اشندر",
"areaTemplate":"بافت روستایی و ویلایی",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},

{
"CityId":621,
"areaName" :"اشندر",
"area type" : "روستا",
"longtitude" :35.70139 ,
"latitude" :52.13383,
"locationDescription":"کوه اشندر",
"subwayAvailability" : "جاده منتهی به چنارشرق",
"busAndTaxi" : "",
"areaNature" : "کوه اشندر،چشمه و چشمه",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},


{
"CityId":621,
"areaName" :"گلگنگک",
"area type" : "محله",
"longtitude" : 35.69892,
"latitude" :52.12447,
"locationDescription":"",
"subwayAvailability" : "جاده چنارشرق",
"busAndTaxi" : "",
"areaNature" : "باغات",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"ویلایی و باغات و کشاورزی ",
},


{
"CityId":621,
"areaName" :"حصار بالا",
"area type" : "محله",
"longtitude" : 35.67605,
"latitude" :52.03863,
"locationDescription":"محلات جنوبی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "روذخانه تار",
"areaTemplate":"",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},

{
"CityId":621,
"areaName" :"حصار پایین",
"area type" : "محله",
"longtitude" :35.66924 ,
"latitude" :52.03260,
"locationDescription":"محلات جنوبی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "رودخانه تار",
"areaTemplate":"بافت قدیم و ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},

{
"CityId":621,
"areaName" :"اصطلک بالا",
"area type" : "محله",
"longtitude" :35.68245 ,
"latitude" :52.06654,
"locationDescription":"",
"subwayAvailability" : "جاده دماوند-فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی ",
},

{
"CityId":621,
"areaName" :"اصطلک پایین",
"area type" : "محله",
"longtitude" :35.67994 ,
"latitude" :52.07547,
"locationDescription":"",
"subwayAvailability" : "جاده دماوند-فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و  کشاورزی ",
},

{
"CityId":621,
"areaName" :"گیلاوند",
"area type" : "محله",
"longtitude" : 35.68396,
"latitude" :52.03691,
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"شهرک شاهد",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"شهرک جهاد",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"شهرک ولیعصر",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},
{
"CityId":621,
"areaName" :"شهرک توحید",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},
{
"CityId":621,
"areaName" :"شهرک سپاه",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"شهرک محک",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},
{
"CityId":621,
"areaName" :"شهرک محک",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"دمادشت",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"مسکن مهر",
"area type" : "محله",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},
{
"CityId":621,
"areaName" :"جیلارد نو",
"area type" : "محله",
"longtitude" :35.68128 ,
"latitude" :52.01492,
"locationDescription":"محلات جنوبی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی  ",
},


{
"CityId":621,
"areaName" :"سنگ پل",
"area type" : "محله",
"longtitude" :35.70771 ,
"latitude" :52.06431,
"locationDescription":"محلات میانی",
"subwayAvailability" : "خیابان فرهنگ",
"busAndTaxi" : "",
"areaNature" : "رودخامه تار",
"areaTemplate":"قدیم و ویلایی",
"facalities" : "صرافی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی  و باغات ",
},

{
"CityId":621,
"areaName" :"مراء",
"area type" : "محله",
"longtitude" :35.65145 ,
"latitude" :52.01436,
"locationDescription":"محلات جنوبی",
"subwayAvailability" : "بلوار شاهد",
"busAndTaxi" : "",
"areaNature" : "رودخانه تار",
"areaTemplate":"بافت قدیم وویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
  "floorArea":"",
"landUse":"مسکونی و باغات  ",
},

{
"CityId":621,
"areaName" :"تمسیان",
"area type" : "روستا",
"longtitude" :35.62309 ,
"latitude" :51.94554,
"locationDescription":"",
"subwayAvailability" : "عبور از روستاهای کاجان و خرمده",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات  ",
},

{
"CityId":621,
"areaName" :"هاشمک",
"area type" : "روستا",
"longtitude" : 35.61582,
"latitude" :52.06384,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "خیابان هاشمک",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی ",
},

{
"CityId":13,
"areaName" :"آبسرد",
"area type" : "محله",
"longtitude" :35.62373 ,
"latitude" :52.16034,
"locationDescription":"",
"subwayAvailability" : "جاده آبسرد",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"بافت ویلایی",
"humanTissue" : "مهاجر و بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی  ",
},
{
"CityId":621,
"areaName" :"قرا",
"area type" : "روستا",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},
{
"CityId":621,
"areaName" :"عینی آباد",
"area type" : "روستا",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"بولان",
"area type" : "روستا",
"longtitude" : "",
"latitude" :"",
"locationDescription":"جاده فیروزکوه",
"subwayAvailability" : "بلوار شهید بهشتی",
"busAndTaxi" : "دارد",
"areaNature" : "",
"areaTemplate":"بافت  قدیم و آپارتمانی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"وادان",
"area type" : "روستا",
"longtitude" : 35.59879,
"latitude" :52.14483,
"locationDescription":"محلات جنوب شرقی",
"subwayAvailability" : "جاده وادان",
"busAndTaxi" : "",
"areaNature" : "کوه عمار",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات  ",
},

{
"CityId":13,
"areaName" :"زان",
"area type" : "روستا",
"longtitude" :35.60452 ,
"latitude" :52.20707,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "آسرد-زان",
"busAndTaxi" : "",
"areaNature" : "چشمه آب ترش",
"areaTemplate":"بافت روستایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات  ",
},

{
"CityId":621,
"areaName" :"آیینه ورزان",
"area type" : "روستا",
"longtitude" : 35.66291,
"latitude" :52.20422,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده آیینه ورزان",
"busAndTaxi" : "",
"areaNature" : "آبشار آیینه ورزان",
"averageTemperature": "",
"areaTemplate":"ویلایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"landUse":"",
"floorArea":"",
"landUse":"مسکونی و باغات  ",
},
{
"CityId":621,
"areaName" :"جابان",
"area type" : "روستا",
"longtitude" :35.64897,
"latitude" :52.25178,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"ویلایی و روستایی",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"باغات و مسکونی",
},

{
"CityId":13,
"areaName" :"سرخه ده",
"area type" : "روستا",
"longtitude" : 35.59854,
"latitude" :52.27297,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده سرخه ده",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"باغات و مسکونی",

},

{
"CityId":621,
"areaName" :"اوچونک",
"area type" : "روستا",
"longtitude" :35.56819 ,
"latitude" :52.23628,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی و مهاجر",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و کشاورزی",
},
{
"CityId":13,
"areaName" :"گرمابسرد",
"area type" : "روستا",
"longtitude" :35.46803,
"latitude" :52.35293,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده گرمابسرد",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی و باغات و کشاورزی",
},
{
"CityId":621,
"areaName" :"سقز دره",
"area type" : "روستا",
"longtitude" :35.51611,
"latitude" :52.39741,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},

{
"CityId":1209,
"areaName" :"قلفک",
"area type" : "روستا",
"longtitude" :35.57649,
"latitude" :52.36341,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده گویج",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},

{
"CityId":1209,
"areaName" :"شاه بلاغی",
"area type" : "روستا",
"longtitude" :35.59716,
"latitude" :52.36353,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده گویج",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},
{
"CityId":621,
"areaName" :"سیدآباد",
"area type" : "روستا",
"longtitude" :35.64071,
"latitude" :52.37155,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

{
"CityId":621,
"areaName" :"آرو",
"area type" : "روستا",
"longtitude" :35.66973,
"latitude" :52.40321,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "بومی",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},

{
"CityId":621,
"areaName" :"کلاک مشهد",
"area type" : "روستا",
"longtitude" :35061763,
"latitude" :52.42644,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},
{
"CityId":621,
"areaName" :"رودافشان",
"area type" : "روستا",
"longtitude" :35.64098,
"latitude" :52.50227,
"locationDescription":"توابع بخش مرکزی",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" :"رودخانه دلی چای و غار رود افشان",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"باغات",
},

{
"CityId":621,
"areaName" :"خسروان",
"area type" : "روستا",
"longtitude" :35.65783,
"latitude" :52.22819,
"locationDescription":"",
"subwayAvailability" : "جاده فیروزکوه",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"باغات",
},


{
"CityId":621,
"areaName" :"مقانک",
"area type" : "روستا",
"longtitude" : 35.55463,
"latitude" :52.26041,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
   
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"landUse":"",
},

{
"CityId":1209,
"areaName" :"کوهان",
"area type" : "روستا",
"longtitude" :35.58110,
"latitude" :52.14369,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
   
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"florArea":"",
"landUse":"",
},
{
"CityId":1209,
"areaName" :"کیلان",
"area type" : "محله",
"longtitude" :35.54819,
"latitude" :52.16566,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"florArea":"",
"landUse":"",
},


{
"CityId":1209,
"areaName" :"زیارت",
"area type" : "روستا",
"longtitude" :35.56707,
"latitude" :52.18484,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"florArea":"",
"landUse":"",
},

{
"CityId":621,
"areaName" :"لومان",
"area type" : "روستا",
"longtitude" :35.58998,
"latitude" :52.18347,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},


{
"CityId":13,
"areaName" :"بیدک",
"area type" : "روستا",
"longtitude" :35.59918,
"latitude" :52.15133,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},

{
"CityId":13,
"areaName" :"اهران",
"area type" : "روستا",
"longtitude" :35.60778,
"latitude" :52.14736,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},

{
"CityId":1209,
"areaName" :"ساران",
"area type" : "روستا",
"longtitude" :35.51239,
"latitude" :52.16881,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"florArea":"",
"landUse":"",
},
{
"CityId":13,
"areaName" :"مرانک",
"area type" : "روستا",
"longtitude" :35.68233,
"latitude" :52.03201,
"locationDescription":"",
"subwayAvailability" : "",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"",
},


{
"CityId":700,
"areaName" :"مهرآباد",
"area type" : "محله",
"longtitude" :35.70254,
"latitude" :51.91621,
"locationDescription":"توابع بخش رودهن",
"subwayAvailability" : "جاده رودهن -دماوند",
"busAndTaxi" : "",
"areaNature" : "",
"areaTemplate":"",
"humanTissue" : "",
"ReginonalPrice": "",
"floorArea":"",
"landUse":"مسکونی",
},

]